cache: bundler

language: ruby

rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.2

sudo: false

branches:
  only: master

before_install:
  - gem update --system
  - gem install -v 1.16.6 bundler

env:
  global:
    - ZUORA_CLIENT_ID=something
    - ZUORA_CLIENT_SECRET=secret
    - ZUORA_DOMAIN=rest.apisandbox.zuora.com
